- name: vars in seperate file
  hosts: frontend
  become: yes
  vars_files:
  - course.yaml
  tasks:
  - name: file vars
    ansible.builtin.debug:
      msg: "Course is {{ course }} and duration is {{ duration }}, trainer name is {{ Trainer }}"