- name: using loop
  hosts: frontend
  become: yes
  tasks:
  - name: loops
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - linux
    - shell
    - ansible 
    - terraform