- name: Install softwares
  hosts: local
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
  
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
  