- name: using filter/functions # used for data manipulation in ansible
  hosts: local
  connection: local
  become: yes
  vars:
    num: 6
    variable: mandatory
    technologies: linux,shell,ansible,terraform,docker
    tags:
      Application: payment
      Environment: dev
  tasks:
  - name: using default
    ansible.builtin.debug:
      msg: "{{ num | default(5) }}"

  - name: using mandatory
    ansible.builtin.debug:
      msg: "{{ variable | mandatory }}"

  - name: string to list
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"

  - name: dictionary to list
    ansible.builtin.debug:
      msg: "{{ dict | dict2items }}"