- name: using filter/functions # used for data manipulation in ansible
  hosts: local
  connection: local
  become: yes
  vars:
    num: 6
    variable: mandatory
    technologies: linux,shell,ansible,terraform,docker
  tasks:
  - name: using default
    ansible.builtin.debug:
      msg: "{{ num | default(5) }}"

  - name: 
    ansible.builtin.debug:
      msg: "{{ variable | mandatory }}"

  - name:
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"