- name: using filter/functions # used for data manipulation in ansible
  hosts: local
  connection: local
  become: yes
  vars:
    num: 6
    variable: mandatory
    technologies: linux,shell,ansible,terraform,docker
    dict:
      Application: payment
      Environment: dev
    tags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: using default
    ansible.builtin.debug:
      msg: "{{ num | default(5) }}"

  - name: using mandatory
    ansible.builtin.debug:
      msg: "{{ variable | mandatory }}"

  - name: string to list
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"

  - name: dictionary to list
    ansible.builtin.debug:
      msg: "{{ dict | dict2items }}"

  - name: list into dictionary
    ansible.builtin.debug:
      msg: "{{ tags | items2dict }}"

  - name: read a file and staore in a variable
    ansible.builtin.set_fact:
      test_file: "{{ lookup('file','sample.yaml') | from_yaml }}"
    
  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ test_file | to_nice_json }}"

  