- name: create user
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check if user exists
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print output
    ansible.builtin.debug:
      msg: "{{ user_output }}"